import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar.jsx";
import Head from "next/head";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontera de Los Andes",
  description: "Generated by Tomas De Paulo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Head></Head>
      <body className={inter.className}>
        <Navbar />
        <div className="fixed right-4 md:right-10 bottom-4 md:bottom-10 z-10" >
          <a
            href="https://api.whatsapp.com/send?phone=5492352409793"
            target="_blank"
          >
            <img src="/images/icons/whatsappBubble.png" alt="Whatsapp" className="w-16 md:w-20"/>
          </a>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
