import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar.jsx";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontera de Los Andes",
  description: "Generated by Tomas De Paulo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} bg-bg-color text-ink antialiased`}>
        <Navbar />
        <div className="fixed right-4 md:right-10 bottom-4 md:bottom-10 z-20">
          <a
            href="https://api.whatsapp.com/send?phone=5492352409793"
            target="_blank"
            className="block shadow-soft rounded-full transition-transform duration-300 hover:scale-110"
          >
            <img src="/images/icons/whatsappBubble.png" alt="Whatsapp" className="w-14 md:w-16" />
          </a>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}